#!/bin/bash

# this is a simple config for herbstluftwm
function hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc detect_monitors

Esetroot -m ~/.wallpapers/wallpaper

hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvtc
hc keybind $Mod-Mod1-Control-l spawn qdbus org.gnome.ScreenSaver / SetActive true
hc keybind $Mod-space spawn bash -c 'exe=`dmenu_path | dmenu -fn "-*-terminus" -nb \#101010 -nf \#eeeeee -i -l 10 -sb \#0099ff -sf \#000000 $@` && exec $exe'

# tags
TAG_NAMES=( {1,2,3,4,5,6,"7:comm","8:office","9:web"} )
TAG_KEYS=( {1..9} )
MAP[0]="(split horizontal:0.5:1 (clients horizontal:0) (clients vertical:0))"
MAP[1]="(split horizontal:0.5:0 (clients vertical:0) (clients vertical:0))"
MAP[2]="(split horizontal:0.5:0 (clients vertical:0) (clients vertical:0))"
MAP[3]="(clients grid:0)"
MAP[4]="(clients grid:0)"

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_KEYS[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    hc load "${TAG_NAMES[$i]}" "${MAP[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc floating 4 on
hc floating 5 on

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# previous tag
hc keybind $Mod-0 use_previous

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-l cycle_layout 1
hc keybind $Mod-g set_layout grid
hc keybind $Mod-f set_layout max
hc keybind $Mod-h set_layout horizontal
hc keybind $Mod-v set_layout vertical

hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.025
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-slash   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

hc set frame_bg_normal_color '#101010'
hc set frame_bg_active_color '#101010'
hc set frame_border_normal_color '#101010'
hc set frame_border_active_color '#99CCFF'
hc set frame_border_width 1
hc set frame_border_inner_width 0
hc set frame_active_opacity 20
hc set frame_normal_opacity 0
hc set frame_gap 10
hc set frame_padding 0
hc set always_show_frame 1
hc set window_border_width 1
hc set window_border_normal_color '#101010'
hc set window_border_active_color '#66CC99'
hc set window_border_urgent_color '#CC6666'
hc set window_gap 10
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'[Pp]inentry' pseudotile=on focus=on manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
hc pad 0 16 0 0 0
hc pad 1 16 0 0 0

panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
    sleep 0.1 && xprop -name "dzen_workspace_panel" -f _NET_WM_WINDOW_TYPE 32a -set _NET_WM_WINDOW_TYPE _NET_WM_WINDOW_TYPE_DOCK
done
pkill -f trayer; trayer --tint 0x101010 --transparent true --alpha 0 --edge top --height 16 --align right --width 200 --widthtype pixel --padding 1 &
